generate_monthly_report:
  description: Generate the end-of-month summary report for a specific month.
  fields:
    year:
      description: The year for which to generate the report.
      example: 2023
      selector:
        number:
          min: 1900
          max: 2100
          mode: box
    month:
      description: The month for which to generate the report (1-12).
      example: 10
      selector:
        number:
          min: 1
          max: 12
          mode: box