name: Badge Reader
version: "0.4.10"
slug: badgereader
init: false
description: "HTTP server to receive badge reader swipes"
arch:
  - amd64
boot: auto
ports:
  8199/tcp: 8199
options:
  notification_domain: "notify"
  notification_service: "quirin_niedernhuber_gmail_com" # Sends using quirin.niedernhuber@gmail.com as sender 
  notification_emails:
    - "quirin.niedernhuber@gmail.com"
  badges:
    - uid: "DE:76:28:3C"
      peopleID: 0
    - uid: "FE:E0:23:3C"
      peopleID: 0
    - uid: "DC:9E:6A:05"
      peopleID: 1
  people:
    - id: 0
      name: "Test Person"
      email: "quirin.niedernhuber@gmail.com"
    - id: 1
      name: "Test Nicole"
      email: "quirin.niedernhuber@gmail.com"
  swipe_debounce_minutes: 1
  swipe_time_buffer_minutes: 3
  storage_backend: "google_sheets"
  storage_file_path: "/data/nas_data/swipe_log.jsonl"
  storage_sheets_dir: "/data/nas_data"
  google_spreadsheet_url: "https://docs.google.com/spreadsheets/d/1qZ3-8Q3z4Nn3q_V3RArP3p8G_sWn3j8aC5H6j2k_4zE/edit#gid=0"
  google_worksheet_name: "Data"
schema:
  notification_domain: str
  notification_service: str
  notification_emails:
    - str
  badges:
    - uid: str
      peopleID: int
  people:
    - id: int
      name: str
      email: str
  swipe_debounce_minutes: int
  swipe_time_buffer_minutes: int
  storage_backend: list(google_sheets|file)
  storage_file_path: str
  storage_sheets_dir: str
  google_spreadsheet_url: url
  google_worksheet_name: str
homeassistant_api: true
map:
  - "addon_config:rw"
  - "share:rw"
  - "data"
  - "/mnt/badge_reader_mount:/data/nas_data:rw"
