name: "NFC Badge Reader Addon"
description: "Reads NFC badges and integrates with Home Assistant"
version: "0.0.7" # Will be updated from manifest.json later
slug: "badgereader_addon"
init: false
arch:
  - amd64
startup: services
boot: auto
ports:
  5060/tcp: 5060 # HTTP server for badge messages runs on port 5060
options: {}
schema: {}
