name: "NFC Badge Reader Addon"
description: "Reads NFC badges and integrates with Home Assistant"
version: "1.0.0" # Will be updated from manifest.json later
slug: "badgereader_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
ports:
  5000/tcp: 5000 # HTTP server for badge messages runs on port 5000
options: {}
schema: {}
