name: "NFC Badge Reader Addon"
description: "Reads NFC badges and integrates with Home Assistant"
version: "0.0.9" # Will be updated from manifest.json later
slug: "badgereader_addon"
init: false
arch:
  - amd64
startup: services
boot: auto
ports:
  8199/tcp: 8199 # HTTP server for badge messages runs on port 8199
options: {}
schema: {}
